update workflow

diff --git a/.github/workflows/turnip.yml b/.github/workflows/turnip.yml
--- a/.github/workflows/turnip.yml
+++ b/.github/workflows/turnip.yml
@@ -1,15 +1,21 @@
-name: nightly-turnip-release
+name: turnip-release
 
 on:
+  push:
+    branches:
+      - main
   workflow_dispatch:
-  schedule:
-  - cron: '30 2 * * *'
+
+env:
+  branch_version: "24.3"
 
 jobs:
-  start_building_turnip:
-    runs-on: ubuntu-24.04
+  start_building_turnip_arm64:
+    runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
 
     - name: Prepare environment
       run: |
@@ -18,40 +24,274 @@ jobs:
         sudo apt update
         sudo apt build-dep mesa -y
     
-    - name: Execute build script
-      run: bash ./turnip_builder.sh
-
-    - name: Upload a Build Artifact
-      uses: actions/upload-artifact@v3.1.0
-      with:
-        name: Upload meson and ninja logs for debugging
-        path: |
-          turnip_workdir/ninja_log
-          turnip_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
-    
-    - id: versions
-      name: "Get release info"
+    - name: Set up Dependencies
       run: |
-        echo "name=$(cat turnip_workdir/release)" >> "$GITHUB_OUTPUT"
-        echo "tag=$(cat turnip_workdir/tag)" >> "$GITHUB_OUTPUT"
-        echo "filename=$(cat turnip_workdir/filename)" >> "$GITHUB_OUTPUT"
-        echo "patched=$(cat turnip_workdir/patched)" >> "$GITHUB_OUTPUT"
+        sudo apt-get update
+        sudo apt-get install -y meson ninja-build patchelf unzip curl python3-pip flex bison zip git dpkg-dev debhelper
+    
+    - name: Install or Upgrade Meson
+      run: |
+        python3 -m pip install --upgrade pip
+        python3 -m pip install --upgrade meson
 
-    - name: Release "turnip"
-      uses: softprops/action-gh-release@v1
-      with:
-        body_path: turnip_workdir/description
-        name: ${{ steps.versions.outputs.name }}
-        tag_name: ${{ steps.versions.outputs.tag }}
-        files: |
-           turnip_workdir/${{ steps.versions.outputs.filename }}.zip
+    - name: Create Work Directory
+      run: |
+        mkdir -p turnip_arm64_workdir
+        cd turnip_arm64_workdir
 
-    - name: Release "turnip" with patched
-      if: ${{ contains(steps.versions.outputs.patched, 'true') }}
-      uses: softprops/action-gh-release@v1
+    - name: Download and Extract Android NDK
+      run: |
+        cd turnip_arm64_workdir
+        ndkver="android-ndk-r26c"
+        if [ ! -d "$ndkver" ]; then
+          curl -LO https://dl.google.com/android/repository/"$ndkver"-linux.zip
+          unzip "$ndkver"-linux.zip
+        fi
+
+    - name: Clone Mesa Source
+      run: |
+        cd turnip_arm64_workdir
+        git clone --depth=1 --branch ${{ env.branch_version }} https://gitlab.freedesktop.org/mesa/mesa.git
+        cd mesa
+
+    - name: Clone and Apply Patches
+      run: |
+        cd $GITHUB_WORKSPACE/turnip_arm64_workdir
+        git clone https://github.com/MastaG/mesa-turnip-ppa.git mesa-turnip
+        cd mesa
+        for patch in $GITHUB_WORKSPACE/turnip_arm64_workdir/mesa-turnip/turnip-patches/*.patch; do
+          echo "Applying patch $patch"
+          git apply "$patch"
+        done
+        echo "All patches applied successfully."
+
+    - name: Build Mesa for Android ARM64
+      run: |
+        cd turnip_arm64_workdir/mesa
+        ndk="$PWD/../android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin"
+        if [ ! -f "$ndk/aarch64-linux-android31-clang" ]; then
+          echo "Compiler not found at $ndk/aarch64-linux-android31-clang" && exit 1
+        fi
+        cat <<EOF > "android-aarch64"
+        [binaries]
+        ar = '$ndk/llvm-ar'
+        c = ['ccache', '$ndk/aarch64-linux-android31-clang']
+        cpp = ['ccache', '$ndk/aarch64-linux-android31-clang++', '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-static-libstdc++']
+        c_ld = 'lld'
+        cpp_ld = 'lld'
+        strip = '$ndk/aarch64-linux-android-strip'
+        pkgconfig = ['env', 'PKG_CONFIG_LIBDIR=$PWD/pkgconfig', '/usr/bin/pkg-config']
+        [host_machine]
+        system = 'android'
+        cpu_family = 'aarch64'
+        cpu = 'armv8'
+        endian = 'little'
+        EOF
+        mkdir -p build-android-aarch64
+        meson setup build-android-aarch64 --cross-file "$PWD/android-aarch64" \
+            -Dbuildtype=release -Dplatforms=android -Dplatform-sdk-version=31 \
+            -Dandroid-stub=true -Dgallium-drivers= -Dvulkan-drivers=freedreno \
+            -Dvulkan-beta=true -Dfreedreno-kmds=kgsl -Db_lto=true
+        ninja -C build-android-aarch64
+
+    - name: Patchelf to Match Soname and Package ARM64
+      run: |
+        cd turnip_arm64_workdir/mesa/build-android-aarch64/src/freedreno/vulkan
+        cp libvulkan_freedreno.so "$GITHUB_WORKSPACE/turnip_arm64_workdir"
+        cd "$GITHUB_WORKSPACE/turnip_arm64_workdir"
+        patchelf --set-soname vulkan.adreno.so libvulkan_freedreno.so
+
+        # Create Debian package structure
+        mkdir -p turnip_${{ env.branch_version }}_arm64/DEBIAN
+        mkdir -p turnip_${{ env.branch_version }}_arm64/usr/lib/aarch64-linux-gnu
+        mkdir -p turnip_${{ env.branch_version }}_arm64/usr/share/vulkan/icd.d
+
+        # Copy files to package structure
+        cp libvulkan_freedreno.so turnip_${{ env.branch_version }}_arm64/usr/lib/aarch64-linux-gnu/libvulkan_freedreno.so
+
+        # Create the ICD JSON file
+        cat <<EOF > turnip_${{ env.branch_version }}_arm64/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json
+        {
+            "ICD": {
+                "api_version": "1.1.274",
+                "library_path": "/usr/lib/aarch64-linux-gnu/libvulkan_freedreno.so"
+            },
+            "file_format_version": "1.0.0"
+        }
+        EOF
+
+        # Create control file
+        cat <<EOL > turnip_${{ env.branch_version }}_arm64/DEBIAN/control
+        Package: mesa-vulkan-drivers
+        Source: mesa
+        Version: ${{ env.branch_version }}-devel-$(date +%Y%m%d)
+        Architecture: arm64
+        Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
+        Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
+        Installed-Size: 26658
+        Depends: libvulkan1, python3:any | python3-minimal:any, libc6 (>= 2.34), libdrm-amdgpu1 (>= 2.4.110), libdrm2 (>= 2.4.99), libelf1 (>= 0.142), libexpat1 (>= 2.0.1), libgcc-s1 (>= 3.0), libllvm15, libstdc++6 (>= 11), libwayland-client0 (>= 1.20.0), libx11-xcb1 (>= 2:1.8.4), libxcb-dri3-0 (>= 1.13), libxcb-present0, libxcb-randr0 (>= 1.13), libxcb-shm0, libxcb-sync1, libxcb-xfixes0, libxcb1 (>= 1.9.2), libxshmfence1, libzstd1 (>= 1.5.2), zlib1g (>= 1:1.1.4)
+        Provides: vulkan-icd
+        Section: libs
+        Priority: optional
+        Multi-Arch: same
+        Homepage: https://mesa3d.org/
+        Description: Mesa Vulkan graphics drivers
+         Vulkan is a low-overhead 3D graphics and compute API. This package
+         includes Vulkan drivers provided by the Mesa project.
+        EOL
+
+        # Build the package
+        dpkg-deb --build turnip_${{ env.branch_version }}_arm64
+
+    - name: Upload ARM64 Artifact to Release
+      uses: softprops/action-gh-release@v2
       with:
-        body_path: turnip_workdir/description
-        name: ${{ steps.versions.outputs.name }}
-        tag_name: ${{ steps.versions.outputs.tag }}
-        files: |
-           turnip_workdir/${{ steps.versions.outputs.filename }}_patched.zip
+        files: ${{ github.workspace }}/turnip_arm64_workdir/turnip_${{ env.branch_version }}_arm64.deb
+        token: ${{ secrets.GITHUB_TOKEN }}
+        name: ubuntu turnip android ${{ env.branch_version }}-devel
+        tag_name: mesa_turnip_${{ env.branch_version }}
+        draft: false
+        prerelease: false
+
+  start_building_turnip_armhf:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v4
+
+    - name: Prepare Environment
+      run: |
+        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
+        sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
+        sudo apt update
+        sudo apt build-dep mesa -y
+
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y meson ninja-build patchelf unzip curl python3-pip flex bison zip git dpkg-dev debhelper
+
+    - name: Install or Upgrade Meson
+      run: |
+        python3 -m pip install --upgrade pip
+        python3 -m pip install --upgrade meson
+
+    - name: Create Work Directory
+      run: |
+        mkdir -p turnip_armhf_workdir
+        cd turnip_armhf_workdir
+
+    - name: Download and Extract Android NDK
+      run: |
+        cd turnip_armhf_workdir
+        ndkver="android-ndk-r26c"
+        if [ ! -d "$ndkver" ]; then
+          curl -LO https://dl.google.com/android/repository/"$ndkver"-linux.zip
+          unzip "$ndkver"-linux.zip
+        fi
+
+    - name: Clone Mesa Source
+      run: |
+        cd turnip_armhf_workdir
+        git clone --depth=1 --branch ${{ env.branch_version }} https://gitlab.freedesktop.org/mesa/mesa.git
+        cd mesa
+
+    - name: Clone and Apply Patches
+      run: |
+        cd $GITHUB_WORKSPACE/turnip_arm64_workdir
+        git clone https://github.com/MastaG/mesa-turnip-ppa.git mesa-turnip
+        cd mesa
+        for patch in $GITHUB_WORKSPACE/turnip_arm64_workdir/mesa-turnip/turnip-patches/*.patch; do
+          echo "Applying patch $patch"
+          git apply "$patch"
+        done
+        echo "All patches applied successfully."
+
+    - name: Build Mesa for ARM (armhf)
+      run: |
+        cd turnip_armhf_workdir/mesa
+        ndk="$PWD/../android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin"
+        if [ ! -f "$ndk/armv7a-linux-androideabi31-clang" ]; then
+          echo "Compiler not found at $ndk/armv7a-linux-androideabi31-clang" && exit 1
+        fi
+        cat <<EOF > "android-armhf"
+        [binaries]
+        ar = '$ndk/llvm-ar'
+        c = ['ccache', '$ndk/armv7a-linux-androideabi31-clang']
+        cpp = ['ccache', '$ndk/armv7a-linux-androideabi31-clang++', '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-static-libstdc++']
+        c_ld = 'lld'
+        cpp_ld = 'lld'
+        strip = '$ndk/arm-linux-androideabi-strip'
+        pkgconfig = ['env', 'PKG_CONFIG_LIBDIR=$PWD/pkgconfig', '/usr/bin/pkg-config']
+        [host_machine]
+        system = 'android'
+        cpu_family = 'arm'
+        cpu = 'armv7'
+        endian = 'little'
+        EOF
+        mkdir -p build-android-armhf
+        meson setup build-android-armhf --cross-file "$PWD/android-armhf" \
+          -Dbuildtype=release -Dplatforms=android -Dplatform-sdk-version=31 \
+          -Dandroid-stub=true -Dgallium-drivers= -Dvulkan-drivers=freedreno \
+          -Dvulkan-beta=true -Dfreedreno-kmds=kgsl -Db_lto=true
+        ninja -C build-android-armhf
+
+    - name: Patch ELF and Package
+      run: |
+        cd turnip_armhf_workdir/mesa/build-android-armhf/src/freedreno/vulkan
+        cp libvulkan_freedreno.so "$GITHUB_WORKSPACE/turnip_armhf_workdir"
+        cd "$GITHUB_WORKSPACE/turnip_armhf_workdir"
+        patchelf --set-soname vulkan.adreno.so libvulkan_freedreno.so
+
+        # Create Debian package structure
+        mkdir -p turnip_${{ env.branch_version }}_armhf/DEBIAN
+        mkdir -p turnip_${{ env.branch_version }}_armhf/usr/lib/arm-linux-gnueabihf
+        mkdir -p turnip_${{ env.branch_version }}_armhf/usr/share/vulkan/icd.d
+
+        # Copy files to package structure
+        cp libvulkan_freedreno.so turnip_${{ env.branch_version }}_armhf/usr/lib/arm-linux-gnueabihf/libvulkan_freedreno.so
+
+        # Create the ICD JSON file
+        cat <<EOF > turnip_${{ env.branch_version }}_armhf/usr/share/vulkan/icd.d/freedreno_icd.armhf.json
+        {
+            "ICD": {
+                "api_version": "1.1.274",
+                "library_path": "/usr/lib/arm-linux-gnueabihf/libvulkan_freedreno.so"
+            },
+            "file_format_version": "1.0.0"
+        }
+        EOF
+
+        # Create control file
+        cat <<EOL > turnip_${{ env.branch_version }}_armhf/DEBIAN/control
+        Package: mesa-vulkan-drivers
+        Source: mesa
+        Version: ${{ env.branch_version }}-devel-$(date +%Y%m%d)
+        Architecture: armhf
+        Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
+        Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
+        Installed-Size: 26658
+        Depends: libvulkan1, python3:any | python3-minimal:any, libc6 (>= 2.34), libdrm-amdgpu1 (>= 2.4.110), libdrm2 (>= 2.4.99), libelf1 (>= 0.142), libexpat1 (>= 2.0.1), libgcc-s1 (>= 3.0), libllvm15, libstdc++6 (>= 11), libwayland-client0 (>= 1.20.0), libx11-xcb1 (>= 2:1.8.4), libxcb-dri3-0 (>= 1.13), libxcb-present0, libxcb-randr0 (>= 1.13), libxcb-shm0, libxcb-sync1, libxcb-xfixes0, libxcb1 (>= 1.9.2), libxshmfence1, libzstd1 (>= 1.5.2), zlib1g (>= 1:1.1.4)
+        Provides: vulkan-icd
+        Section: libs
+        Priority: optional
+        Multi-Arch: same
+        Homepage: https://mesa3d.org/
+        Description: Mesa Vulkan graphics drivers
+         Vulkan is a low-overhead 3D graphics and compute API. This package
+         includes Vulkan drivers provided by the Mesa project.
+        EOL
+
+        # Build the package
+        dpkg-deb --build turnip_${{ env.branch_version }}_armhf
+
+    - name: Upload ARMHF Artifact to Release
+      uses: softprops/action-gh-release@v2
+      with:
+        files: ${{ github.workspace }}/turnip_armhf_workdir/turnip_${{ env.branch_version }}_armhf.deb
+        token: ${{ secrets.GITHUB_TOKEN }}
+        name: ubuntu turnip android ${{ env.branch_version }}-devel
+        tag_name: mesa_turnip_${{ env.branch_version }}
+        draft: false
+        prerelease: false
